clear all;
close all;
clc;
addpath '/Users/zhangchi8620/Data/Human-Skeleton/HDM05/dataset/mfile'

%%

label = {'drink', ...
         'eat', ...
         'read book',...
         'call phone', ...
         'write', ...
         'use laptop',...
         'use vacu.',...
         'cheer up',...
         'sit stil.',...
         'toss paper',...
         'play game',...
         'lie down',...
         'walk',...
         'play guitar',...
         'stand up',...
         'sit down'
};
     
     
% label= {'depo. flo.',...
%         'elbo. kne.',...
%         'grab high',...
%         'hop leg.',...
%         'jog',...
%         'kick forw.',...
%         'lie flo.',...
%         'rot. arm.',...
%         'sneak',...
%         'squat',...
%         'thr. bas.'};
     
load('cmat.mat');
%%
cmat = cmat;


n_class = length(cmat);
for i = 1:n_class
   cmat(i,:) = cmat(i,:) ./ sum(cmat(i,:)); 
end

drawConfusionMatrix(cmat, label);



